DO $$
    DECLARE -- Any variable declarations would go here

    BEGIN --Begin transaction

        INSERT INTO department (name)
        VALUES 
        ('Engineering'), --1 is id..SERIAL so autogenerated
        ('Finance'), --2
        ('Legal'), ---3
        ('Sales'), --4
        ('Service'); --5

        INSERT INTO role (title, salary, department_id)
        VALUES
        ('Sales Lead', 100000, 4),--1--num given for role_id?
        ('Salesperson', 80000, 4),--2
        ('Lead Engineer', 150000, 1),--3
        ('Software Engineer', 120000, 1),--4
        ('Account Manager', 160000, 2),--5
        ('Accountant', 125000, 2), --6
        ('Legal Team Lead', 250000, 3),--7
        ('Lawyer', 190000, 3);--8

        INSERT INTO employee (first_name, last_name, role_id, manager_id)
        VALUES
        ('John','Doe', 1, null),--null bc John doesnt have a manager? John is a manager.if he did, we would change null to a number that correlates to his managers employee_id 
        ('Mike', 'Chan', 2, 1),
        ('Ashley', 'Rodriguez', 3, null),
        ('Kevin', 'Tupik', 4, 3),--Ashley is Kevin's mananger
        ('Kunal', 'Singh', 5, null),
        ('Malia', 'Brown', 6, 5),
        ('Sarah', 'Lourd', 7, null),
        ('Tom', 'Allen', 8, 7);


RAISE NOTICE 'Transaction complete';

EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Error occured: %', SQLERRM;
        ROLLBACK;
END $$;